apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: katib-suggestion-bayesianoptimization
  namespace: kubeflow
  labels:
    app: katib
    component: suggestion-bayesianoptimization
spec:
  replicas: 1
  template:
    metadata:
      name: katib-suggestion-bayesianoptimization
      labels:
        app: katib
        component: suggestion-bayesianoptimization
    spec:
      containers:
      - name: katib-suggestion-bayesianoptimization
        image: katib/v1alpha2/suggestion-bayesianoptimization
        imagePullPolicy: IfNotPresent
        ports:
        - name: api
          containerPort: 6789
