apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-suggestion-hyperband
  namespace: kubeflow
  labels:
    app: vizier
    component: suggestion-hyperband
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-suggestion-hyperband
      labels:
        app: vizier
        component: suggestion-hyperband
    spec:
      containers:
      - name: vizier-suggestion-hyperband
        image: katib/v1alpha1/suggestion-hyperband
        ports:
        - name: api
          containerPort: 6789
