apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-suggestion-random
  namespace: kubeflow
  labels:
    app: vizier
    component: suggestion-random
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-suggestion-random
      labels:
        app: vizier
        component: suggestion-random
    spec:
      containers:
      - name: vizier-suggestion-random
        image: katib/v1alpha1/suggestion-random
        ports:
        - name: api
          containerPort: 6789
