apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-core-rest
  namespace: kubeflow
  labels:
    app: vizier
    component: core-rest
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-core-rest
      labels:
        app: vizier
        component: core-rest
    spec:
      containers:
      - name: vizier-core-rest
        image: katib/v1alpha1/vizier-core-rest
        command:
          - './vizier-manager-rest'
        ports:
        - name: api
          containerPort: 80
