apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-earlystopping-medianstopping
  namespace: kubeflow
  labels:
    app: vizier
    component: earlystopping-medianstopping
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-earlystopping-medianstopping
      labels:
        app: vizier
        component: earlystopping-medianstopping
    spec:
      containers:
      - name: vizier-earlystopping-medianstopping
        image: katib/v1alpha1/earlystopping-medianstopping
        ports:
        - name: api
          containerPort: 6789
