apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: katib-suggestion-nasrl
  namespace: kubeflow
  labels:
    app: katib
    component: suggestion-nasrl
spec:
  replicas: 1
  template:
    metadata:
      name: katib-suggestion-nasrl
      labels:
        app: katib
        component: suggestion-nasrl
    spec:
      containers:
      - name: katib-suggestion-nasrl
        image: katib/v1alpha2/suggestion-nasrl
        ports:
        - name: api
          containerPort: 6789
